### ISSUE TITLE
Checking for missing value?

### ISSUE THREAD

**Issue by martikaljuve** [infinum/react-mobx-translatable#1]
It would be nice to have `I18n.has` available in addition to `I18n.t`, or have an option in `I18n-harmony` to return something falsey for missing values. Right now I'm checking for missing values like this:

``` jsx
var translationKey = 'someTranslationKey';
var translation = this.t(translationKey);
var hasTranslation = translation !== translationKey;

return (
    <div>
        {hasTranslation && <p>{translation}</p>}
    </div>
);
```

With `I18n.has` available as `this.has`, I could reduce it to this:

``` jsx
var translationKey = 'someTranslationKey';

return (
    <div>
        {this.has(translationKey) && <p>{this.t(translationKey)}</p>}
    </div>
);
```

Or with falsey values from `I18n.t`, I could reduce it to this:

``` jsx
var translation = this.t('someTranslationKey');

return (
    <div>
        {!!translation && <p>{translation}</p>}
    </div>
);
```

**Comment by andreicek** [comment]
The change for `has` was merged just now. This will be available in `v1.2.0`.

**Comment by DarkoKukovec** [comment]
Hi @martikaljuve, version 1.2.0 was just published on npm.

**Comment by martikaljuve** [comment]
Awesome work, thanks! :+1:
